### ISSUE TITLE
discussion on document and make decisions

### ISSUE THREAD

**Issue by SakineMazlomyar** [SakineMazlomyar/TechStore#1]

**Comment by MisticG** [comment]
I suggest that:

1. I will make the code for the what the buttons will do in JS. Because there was alot of buttons that did different things... So I should at least start with those. 

2. All images should be in a folder.

3. I think we should have div id/classes in html so we can manipulate them easier through Jquery and css/bootstrap.

**Comment by SakineMazlomyar** [comment]
I have them in the folder now. I just needed to add directory in json file and that was it.
so now the pictures are fine,

I just created one more function with the properties of every pictures , there is only one button which I added today

**Comment by vogelsara** [comment]
Great! please first check my idea about the concept of make more parts from addingPropertyToProduct function because it gets a mess. nobody will understand it. we should make little parts as "addButton" and then insert it to addingPropertyToProduct function. with it, it will be more clear and easily changable.
